### ISSUE TITLE
R check error

### ISSUE THREAD

**Issue by andybega** [Nicolas-Schmidt/BayesMFSurv#1]
Hi guys, 

I tried rebuilding the package using the latest from GH (I cloned your repo), and: 

1. Some of the documentation is out of date (I ran `devtools::document()` and there were some minor changes).
2. R check is throwing an error:

```
── Building ───────────────────────────────────────────────────────────── BayesMFSurv ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘/Users/andybega/Work/BayesMFSurv/DESCRIPTION’ ...
─  preparing ‘BayesMFSurv’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘BayesMFSurv_0.2.0.tar.gz’
   
── Checking ───────────────────────────────────────────────────────────── BayesMFSurv ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/Users/andybega/Work/BayesMFSurv.Rcheck’
─  using R version 3.6.1 (2019-07-05)
─  using platform: x86_64-apple-darwin15.6.0 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✓  checking for file ‘BayesMFSurv/DESCRIPTION’ ...
─  checking extension type ... Package
─  this is package ‘BayesMFSurv’ version ‘0.2.0’
─  package encoding: UTF-8
✓  checking package namespace information ...
E  checking package dependencies (3.5s)
   Namespace dependency not required: ‘RcppArmadillo’
   
   See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
   manual.
   
   See
     ‘/Users/andybega/Work/BayesMFSurv.Rcheck/00check.log’
   for details.
   
── R CMD check results ────────────────────────────────── BayesMFSurv 0.2.0 ────
Duration: 3.9s

> checking package dependencies ... ERROR
  Namespace dependency not required: ‘RcppArmadillo’
  
  See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
  manual.

1 error x | 0 warnings ✓ | 0 notes ✓
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

Adding RcppArmadillo to imports in the DESCRIPTION fixes this and R check runs without errors, warnings, notes.

**Comment by Sergio-Bejar** [comment]
Hi Andy, 

Thanks for the time you spent reviewing our submission.   Below, please find our response to this point. 

R: This is a good point.  We had a similar issue when we submitted our package to CRAN R.  The problem itself is not necessarily with the dependency of 'RccpArmadillo', but with the default compilation of the 'NAMESPACE' file that is generated when one executes devtools::documents().  Specifically, the aforementioned function generates importFrom[(RccpArmadillo & importFrom(RccpsourceCpp)] in the 'NAMESPACE' file when it should only import 'Rccp' in 'evalCpp' and not ''RccpArmadillo'.  

Therefore, to prevent issues/errors during the R CMD check when using devtools it is necessary to be specific about the files one wants to compile.  That is, we should compile the files with extension rd but not the 'NAMESPACE' file.    To compile the package  in a local station, we suggest using: devtools::documents(roclets = 'rd').

**Comment by andybega** [comment]
Hi Sergio!
`mfsurv.R` has directives at the top to import `RcppArmadillo` and `Rcpp::sourceCpp`:

```r
#' @import RcppArmadillo
#' @importFrom Rcpp sourceCpp
```

Since those are not needed (yes?), what about just taking them out? That will fix the problem with using plain `devtools::document()`, i.e. including NAMESPACE generation, and also fixes the R check error.

**Comment by Nicolas-Schmidt** [comment]
Hi @andybega!

Oh, you're right!
Until now we have not realized that it was a comment from roxygen2 (# ') instead of a simple comment (#). We have already fixed it.

Thank you!
