### ISSUE TITLE
Both authors and authors@R in DESCRIPTION

### ISSUE THREAD

**Issue by andybega** [Nicolas-Schmidt/BayesMFSurv#2]
Both the the Author and Authors@R fields in the DESCRIPTION are specified, and the entries don't match. Maybe just keep Authors@R?

<img width="1052" alt="Screen Shot 2020-03-20 at 19 57 08" src="https://user-images.githubusercontent.com/1353756/77193876-9ea7ad00-6ae7-11ea-9486-569802bf7355.png">

https://github.com/openjournals/joss-reviews/issues/2164

**Comment by Sergio-Bejar** [comment]
We updated the description file in our repo.  Thanks for catching this mistake!
