### ISSUE TITLE
Better README examples?

### ISSUE THREAD

**Issue by andybega** [Nicolas-Schmidt/BayesMFSurv#4]
There are two example models in the README, one for for the misclassified failure model (MF, `mfsurv`) and one without (`mcmcsurv`). Both use the RBS data. 

I have two suggestions for improving the README examples. 

## 1. Faster examples

I gave up on the first example after 3 minutes, the second one took me 7 minutes to run. IMO the REAMDE examples should give users a foothold on your core functions/API, for which that kind of delay is not very helpful. 

One option would be to include saved versions of these models in the package as data. You already have these in any case under `data-raw` and use them in `README.Rmd`, I guess, to avoid having to run the full models when compiling the markdown README. 

The other one would be find or create a new example or some other way to cut down the time the current examples need to run. 

## 2. MF motivation

If I understand right, `mcmcsurv` is a Bayesian equivalent of regular survival models estimated via MLE, and `mfsurv`, in addition to the Bayesian aspect, accounts for mis-classified failures. It might be helpful in the README to add very short description in each respective example clarifying this, and for the MF version, also a short plain English explanation for when and why someone might want to use this. People who have not seen the PA paper might come across this.

**Comment by andybega** [comment]
What about echoing the code in lines 147 on in README.Rmd that you use to generate the posterior density plots? Right now it kind of looks like it's part of some package command that is missing from the example.

**Comment by Sergio-Bejar** [comment]
1. Faster Examples
We created (and posted) in the README file new examples that run much faster.  In addition, we provide users with a link where they can find the results of both examples with a larger number of iterations.   

2. MF Motivation
This is a good point.  We incorporated this suggestion in the README as well.
