### ISSUE TITLE
print/plot methods for mfsurv and mcmcsurv objects?

### ISSUE THREAD

**Issue by andybega** [Nicolas-Schmidt/BayesMFSurv#5]
Without a print method it defaults to printing the whole object/list, which can get quite long. 

For plot, you have trace plots and posterior plots in the README example, how about making a very short plot method for those?

**Comment by Sergio-Bejar** [comment]
This is a very good point.  We considered creating 'print()' and 'plot()' methods for the package.  Yet we believe that existing functions already allow users to create the plots.  That said, we do not rule out the possibility of creating the aforementioned methods in a future update of our package.

**Comment by andybega** [comment]
Thanks. I will go ahead and close this then as well.
